---
# Use this for inspiration
# https://dev.to/wayofthepie/ephemeral-self-hosted-github-actions-runners-1h5m

# - name: Download actions-runner tar.gz
#   get_url:
#     url: https://github.com/actions/runner/releases/download/v2.273.0/actions-runner-linux-x64-2.273.0.tar.gz
#     dest: /tmp/actions-runner.tar.gz

# - name: Ensure directy exists
#   file:
#     path: /home/admin/actions-runner/
#     state: directory

# - name: Unarchive file
#   unarchive:
#     src: /tmp/actions-runner.tar.gz
#     dest: /home/admin/actions-runner/
#     remote_src: yes

# - name: Unconfigure
#   shell: ./config.sh remove --token AASJ3UNS2C76DHAEHBX3EQ27I6YTU --name infrastructure-gitlab-runner
#   args:
#     chdir: /home/admin/actions-runner/

# - name: Configure
#   shell: ./config.sh --url https://github.com/Mads-Andersen/infrastructure --token AASJ3UNS2C76DHAEHBX3EQ27I6YTU --name infrastructure-gitlab-runner --unattended --replace
#   args:
#     chdir: /home/admin/actions-runner/

- name: Create service script
  copy:
    src: "{{ item.source }}"
    dest: "{{ item.destination }}"
    mode: '{{ item.mode }}'
  become: true
  loop:
    - { source: 'github-actions-runner.service', destination: '/etc/systemd/system/github-actions-runner.service', mode: '0755' }

- name: Enable and start service
  service:
    name: github-actions-runner
    enabled: true
    state: restarted
  become: true